Syntax 4

SectionVerb {
    EnableSequence [
        cset "name='WSA_CODEC_DMA_RX_0 Audio Mixer MultiMedia1' 1"
    ]
    DisableSequence [
        cset "name='WSA_CODEC_DMA_RX_0 Audio Mixer MultiMedia1' 0"
    ]
    Value {
        TQ "HiFi"
    }
}

SectionDevice."Speaker" {
    Comment "Yoga Tweeters"
    
    Value {
        PlaybackPriority 100
        PlaybackPCM "hw:X1E80100LENOVOY,0"
    }

    EnableSequence [
        cset "name='TweeterLeft COMP Switch' 1"
        cset "name='TweeterRight COMP Switch' 1"
        
        cset "name='TweeterLeft PA Volume' 12"
        cset "name='TweeterRight PA Volume' 12"
        
        cset "name='TweeterLeft DAC Switch' on"
        cset "name='TweeterRight DAC Switch' on"
    ]

    DisableSequence [
        cset "name='TweeterLeft DAC Switch' off"
        cset "name='TweeterRight DAC Switch' off"
        cset "name='TweeterLeft COMP Switch' 0"
        cset "name='TweeterRight COMP Switch' 0"
    ]
}
