context.modules = [
    { name = libpipewire-module-filter-chain
        args = {
            node.description = "Yoga Slim 7x DSP Crossover "
            media.name       = "Yoga Slim 7x DSP Crossover "
            filter.graph = {
                nodes = [
                    {
                        type = builtin
                        name = hrtf_convolver
                        label = convolver
                        control = { "Filename" = "filter.wav" }
                    }

                    {
                        type  = builtin
                        name  = eq_tw_l
                        label = bq_highpass
                        control = { "Freq" = 800.0 "Q" = 0.707 }
                    }
                    {
                        type  = builtin
                        name  = eq_tw_r
                        label = bq_highpass
                        control = { "Freq" = 800.0 "Q" = 0.707 }
                    }

                    {
                        type  = builtin
                        name  = eq_wf_l
                        label = bq_lowpass
                        control = { "Freq" = 2000.0 "Q" = 0.707 }
                    }
                    {
                        type  = builtin
                        name  = eq_wf_r
                        label = bq_lowpass
                        control = { "Freq" = 2000.0 "Q" = 0.707 }
                    }
                    
                    {
                        type  = builtin
                        name  = limiter
                        label = compressor
                        control = { "Threshold" = -3.0 "Ratio" = 10.0 "Attack" = 2.0 "Release" = 20.0 }
                    }
                ]
                
                links = [
                    { output = "hrtf_convolver:Out 1" input = "eq_tw_l:In" }
                    { output = "hrtf_convolver:Out 1" input = "eq_wf_l:In" }
                    
                    { output = "hrtf_convolver:Out 2" input = "eq_tw_r:In" }
                    { output = "hrtf_convolver:Out 2" input = "eq_wf_r:In" }

                    { output = "eq_tw_l:Out" input = "limiter:In 1" }
                    { output = "eq_tw_r:Out" input = "limiter:In 2" }
                    { output = "eq_wf_l:Out" input = "limiter:In 3" }
                    { output = "eq_wf_r:Out" input = "limiter:In 4" }
                ]
                
                inputs  = [ "hrtf_convolver:In 1" "hrtf_convolver:In 2" ]
                
                outputs = [ "limiter:Out 1" "limiter:Out 2" "limiter:Out 3" "limiter:Out 4" ]
            }
            capture.props = {
                node.name      = "capture.crossover"
                media.class    = Audio/Sink
                audio.channels = 2
                audio.position = [ FL FR ]
            }
            playback.props = {
                node.name      = "playback.crossover"
                node.passive   = true
                audio.channels = 4
                audio.position = [ FL FR RL RR ]
                target.object  = "alsa_output.hw_0_0" 
            }
        }
    }
]
